### ISSUE TITLE
React-router config

### ISSUE THREAD

**Issue by nmiguelmoura** [pkellner/pluralsight-course-react-aspnet-core#2]
Hi, sorry to post here but didn't know were else to report this.
In Adding React Router to the App step, I had to add to webpack.config.js the following:
devServer: {
        contentBase: PUBLIC_DIR,
        port: 9000,
        open: true,
        **historyApiFallback: true,**
    }
If not, only the "/" router is loaded.
Thanks for the nice course

**Comment by pkellner** [comment]
Thanks @nmiguelmoura I've updated both the course and the repo here to reflect the change you mention.
