### ISSUE TITLE
webpack command doesn't work on the command line

### ISSUE THREAD

**Issue by cataquil** [pkellner/pluralsight-course-react-aspnet-core#4]
when installed locally ie. --save-dev 'webpack' command doesn't work on the command prompt

**Comment by pkellner** [comment]
Can you try this command? (if mac, might need sudo or in windows run as admin command prompt)

npm install --global webpack

**Comment by pkellner** [comment]
Yes on WebPack 3. Originally, I had not pinned WebPack 3 and that lead to a lot of unhappy viewers when all my source code broke. Now that it is pinned, there should not be an issue.  I do think that you should be able to install webpack with the command above and everything will work correctly. If it does not, LMK as much config info as you can about your system and I'll see what I can do to test and fix.  I always test all my source with just `npm install` at a command prompt so there is no webstorm dependency.

**Comment by cataquil** [comment]
I got it to work with webpack 4
